# Generated by Django 6.0.7 on 2026-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Study', 'Study'), ('Work', 'Work'), ('Personal', 'Personal'), ('Project', 'Project'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
